services:
  - type: web
    name: simple-task-manager
    env: docker
    plan: free
    region: oregon
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
